

spring.application.name=cinsas-do-amanha-backend
server.port=${PORT:8080}
supabase.name=qdexsnqblqhmssjjkgja

# --- DATABASE CONFIGURATION ---
spring.datasource.url=jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-update=true

# --- SECURITY: SUPABASE JWT VALIDATION ---
# --- SEGURANCA: VALIDACAO DE JWT DO SUPABASE ---
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${supabase.name}.supabase.co/auth/v1